# Generated by Django 3.1.7 on 2021-04-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
